version: "3"
services:
  backend:
    privileged: true
    network_mode: host # --network host
    restart: always
    build: .
    ports:
      - 2017:2017
      - 12345:12345
    volumes:
      - shared-data:/etc/v2ray
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      
  v2ray:
    privileged: true
    network_mode: host # --network host
    restart: always
    image: "v2ray/official"
    pid: service:backend
    environment:
     - V2RAY_LOCATION_ASSET=/etc/v2ray
    ports:
      - 20170-20172:20170-20172
      - 12345:12345
    volumes:
      - shared-data:/etc/v2ray
    entrypoint: sh -c "cp -rfu /usr/bin/v2ray/* /etc/v2ray && v2ray -config=/etc/v2ray/config.json"

volumes:
  shared-data:
